
import React from 'react';
import { ArrowRight, FileSpreadsheet, FileImage, BrainCircuit, CheckCircle, Upload } from 'lucide-react';

interface Props {
  onStart: () => void;
}

export const LandingPage: React.FC<Props> = ({ onStart }) => {
  return (
    <div className="flex flex-col items-center justify-center py-12 px-4 animate-in fade-in duration-700">
      
      {/* Hero Section */}
      <div className="text-center max-w-4xl mx-auto mb-16">
        <div className="inline-flex items-center gap-2 bg-brand-50 dark:bg-brand-900/20 text-brand-700 dark:text-brand-300 px-4 py-2 rounded-full text-sm font-semibold mb-6 shadow-sm border border-brand-100 dark:border-brand-800/50">
          <BrainCircuit size={18} />
          <span>Powered by Gemini 2.5 Flash</span>
        </div>
        <h1 className="text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight mb-6 leading-tight">
          Automated Reconciliation for <br/>
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-600 to-purple-600 dark:from-brand-400 dark:to-purple-400">
            Multi-Store Retail
          </span>
        </h1>
        <p className="text-xl text-slate-600 dark:text-slate-400 mb-10 max-w-2xl mx-auto leading-relaxed">
          Stop manually checking receipts. Instantly reconcile your <strong>Billing Machine Excel</strong> reports against <strong>Handwritten Store Logs</strong> using AI.
        </p>
        <button 
          onClick={onStart}
          className="group relative inline-flex items-center justify-center px-8 py-4 text-lg font-bold text-white transition-all duration-200 bg-brand-600 rounded-full hover:bg-brand-700 hover:shadow-lg hover:-translate-y-0.5 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand-500 dark:focus:ring-brand-400"
        >
          Start Reconciliation
          <ArrowRight className="ml-2 w-5 h-5 group-hover:translate-x-1 transition-transform" />
        </button>
      </div>

      {/* How it Works / 3 Steps */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto w-full">
        
        {/* Step 1 */}
        <div className="bg-white dark:bg-slate-800 p-8 rounded-2xl border border-gray-100 dark:border-slate-700 shadow-xl shadow-gray-200/50 dark:shadow-black/20 hover:shadow-2xl hover:shadow-brand-100/50 dark:hover:shadow-brand-900/10 transition-all duration-300 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <span className="text-9xl font-bold text-brand-900 dark:text-brand-500">-1-</span>
          </div>
          <div className="w-14 h-14 bg-brand-100 dark:bg-brand-900/30 text-brand-600 dark:text-brand-300 rounded-2xl flex items-center justify-center mb-6 shadow-inner">
            <FileSpreadsheet size={28} />
          </div>
          <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3">1. Upload System Data</h3>
          <p className="text-gray-500 dark:text-gray-400 leading-relaxed">
            Import the Excel report generated by your billing machine. This defines the <strong>expected revenue</strong> (Cash, UPI, Card) for each store.
          </p>
        </div>

        {/* Step 2 */}
        <div className="bg-white dark:bg-slate-800 p-8 rounded-2xl border border-gray-100 dark:border-slate-700 shadow-xl shadow-gray-200/50 dark:shadow-black/20 hover:shadow-2xl hover:shadow-purple-100/50 dark:hover:shadow-purple-900/10 transition-all duration-300 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <span className="text-9xl font-bold text-purple-900 dark:text-purple-500">-2-</span>
          </div>
          <div className="w-14 h-14 bg-purple-100 dark:bg-purple-900/30 text-purple-600 dark:text-purple-300 rounded-2xl flex items-center justify-center mb-6 shadow-inner">
            <FileImage size={28} />
          </div>
          <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3">2. Upload Physical Reports</h3>
          <p className="text-gray-500 dark:text-gray-400 leading-relaxed">
            Drag & drop photos of the <strong>handwritten daily closing notes</strong>. The AI automatically matches them to the correct store and date.
          </p>
        </div>

        {/* Step 3 */}
        <div className="bg-white dark:bg-slate-800 p-8 rounded-2xl border border-gray-100 dark:border-slate-700 shadow-xl shadow-gray-200/50 dark:shadow-black/20 hover:shadow-2xl hover:shadow-green-100/50 dark:hover:shadow-green-900/10 transition-all duration-300 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
            <span className="text-9xl font-bold text-green-900 dark:text-green-500">-3-</span>
          </div>
          <div className="w-14 h-14 bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-300 rounded-2xl flex items-center justify-center mb-6 shadow-inner">
            <CheckCircle size={28} />
          </div>
          <h3 className="text-xl font-bold text-gray-900 dark:text-white mb-3">3. Instant Verification</h3>
          <p className="text-gray-500 dark:text-gray-400 leading-relaxed">
            Gemini reads the handwriting (even with bank slips stapled on top), calculates variances, and generates a <strong>clean audit report</strong>.
          </p>
        </div>

      </div>

      <div className="mt-20 border-t border-gray-200 dark:border-slate-800 pt-10 text-center">
        <p className="text-sm text-gray-400 dark:text-gray-500 font-medium uppercase tracking-widest mb-4">Supported Formats</p>
        <div className="flex justify-center gap-8 opacity-60 grayscale hover:grayscale-0 transition-all duration-500">
          <div className="flex items-center gap-2 font-semibold text-gray-600 dark:text-gray-400">
            <FileSpreadsheet size={20} /> .XLSX / .XLS
          </div>
          <div className="flex items-center gap-2 font-semibold text-gray-600 dark:text-gray-400">
            <FileImage size={20} /> JPG / PNG / HEIC
          </div>
        </div>
      </div>

    </div>
  );
};
